server:
  port: 8030
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-eureka-user-hystrix
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true