server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-gataway-zuul
zuul:
  routes:
   order-serviceId:  #zuul唯一标识
     path: /order/** #需要映射的路径
     service-id: microservice-eureka-client-producer #Eureka中的serviceId
